valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test1.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test2.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s linux grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s MacOS grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s macos grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s grep grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s tennis grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -i sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -v sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -c sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -l sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -n sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -h sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test3.txt > grep_output
valgrind --tool=memcheck --leak-check=yes ./s21_grep -s sky grep_test3.txt > grep_output
